### ISSUE TITLE
The link to the raw data download cannot be accessed. Would you please re-upload it?

### ISSUE THREAD

**Issue by hyaihjq** [mingdianliu/astra-toolbox-for-cone-beam#1]

**Comment by hyaihjq** [comment]
thanks!!!

**Comment by hyaihjq** [comment]
![image](https://github.com/mingdianliu/astra-toolbox-for-cone-beam/assets/27874026/45b714cb-c6b6-4206-8e6b-bf5d7f76dc77)

**Comment by hyaihjq** [comment]
可以回复一下么？谢谢

**Comment by mingdianliu** [comment]
Please use this new link to download the data. https://iastate.box.com/s/ouz0rjjb6g1b5queqtpr6pee5upb8s5r

**Comment by mingdianliu** [comment]
Please use this new link to download the data.

**Comment by hyaihjq** [comment]
thanks

**Comment by qimu-xieguangkun** [comment]
The link to the raw data download cannot be accessed. Would you please re-upload it again?

**Comment by mingdianliu** [comment]
> The link to the raw data download cannot be accessed. Would you please re-upload it again?

Please send an email to me (lmdvigor@gmail.com) to access the link.
